### ISSUE TITLE
Not ready. Please check your connection

### ISSUE THREAD

**Issue by chungyan5** [bbinet/docker-teamviewer#2]
hi, 
I can start the image on my ubuntu 16.04 desktop, however, it seems cannot connect to my network. Any configuration i need to set for internet connection?

thanks
yan

**Comment by stefhenry** [comment]
same issue here. Did you fix it?

I noticed there is internet inside container indeed, but TV still showing "not ready"

**Comment by bbinet** [comment]
No, it never worked for me neither...

**Comment by linuxoid69** [comment]
![1](https://user-images.githubusercontent.com/2655695/49669312-0e6c6280-fa72-11e8-9522-86768d8d35d3.png)
I set accept in settings "incoming lan connection". This is solved the problem.
However, i not checked work.

**Comment by cbcalves** [comment]
Start the "teamviewerd" before the gui.

`CMD sudo /etc/init.d/teamviewerd start`
`CMD teamviewer`

Although it don't show the ID and PASSWORD for me, I guess something is still missing, now it is ready to connect.
